server:
  port: 8080
jwt:
  secret: "923423mfsfmsfmdmfmsm3232523mslbdba67"
  lifetime: 30m
spring:
  application:
    name: bank_app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: iamroot
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    enabled: true



